name: Docker Image && Kubernetes Release

on:
  push:
    branches:
      - main
    paths:
      - 'group_vars/all.yml'

  pull_request:
    branches:
      - main
    paths:
      - 'group_vars/all.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install docker pyyaml

    - name: Run script
      env:
        ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
        ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      run: |
        python k8s.py

    - name: Get k8s Version
      id: get_version
      run: |
        k8s_version=$(python -c "import yaml; data = yaml.safe_load(open('group_vars/all.yml')); print(data['kubernetes']['version'])")
        echo "k8s_version=$k8s_version" >> $GITHUB_ENV

    - name: Check if tag exists
      id: check_tag
      run: |
        if git ls-remote --tags origin | grep -q "refs/tags/${{ env.k8s_version }}"; then
          echo "Tag exists"
          echo "tag_exists=true" >> $GITHUB_ENV
        else
          echo "Tag does not exist"
          echo "tag_exists=false" >> $GITHUB_ENV

    - name: Download
      if: env.tag_exists == 'false'
      run: |
        wget https://dl.k8s.io/release/${{ env.k8s_version }}/bin/linux/amd64/kubectl
        wget https://dl.k8s.io/release/${{ env.k8s_version }}/bin/linux/amd64/kube-apiserver
        wget https://dl.k8s.io/release/${{ env.k8s_version }}/bin/linux/amd64/kube-controller-manager
        wget https://dl.k8s.io/release/${{ env.k8s_version }}/bin/linux/amd64/kube-scheduler
        wget https://dl.k8s.io/release/${{ env.k8s_version }}/bin/linux/amd64/kubelet
        wget https://dl.k8s.io/release/${{ env.k8s_version }}/bin/linux/amd64/kube-proxy
      
    - name: Push Release
      uses: softprops/action-gh-release@v2
      if: env.tag_exists == 'false'
      with:
        token: ${{ secrets.GIT_TOKEN }}
        tag_name:  ${{ env.k8s_version }}
        preserve_order: true
        files: |
          kubectl
          kube-apiserver
          kube-controller-manager
          kube-scheduler
          kubelet
          kube-proxy
