name: Docker Image && Kubernetes Release

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wget docker pyyaml PyGithub requests

    - name: Run script
      env:
        ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
        ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        GIT_REPOS: ${{ github.repository }}
      run: |
        python k8s.py